name: 'Sample Workflow'
on:
  push:
    branches:
      - 'master'
jobs:
  hello:
    name: 'Hello Job'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v3'
      - name: 'Deploy'
        run: |
          git config -l > abc.txt
          git add abc.txt
          git -c user.name=github-actions -c user.email=github-actions@github.com commit --author 'Github CI <github-ci@github.com>' -m 'Autocommit'
          git push
