name: 'Sample Workflow'
on:
  push:
    branches:
      - 'master'
jobs:
  hello:
    name: 'Hello Job'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/setup-node@v3'
      - name: 'Print Node.js version'
        run: |
          node --version
