name: 'Sample Workflow'
on:
  push:
    branches:
      - 'master'
jobs:
  hello:
    name: 'Hello Job'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'actions/setup-node@v3'
      - name: 'Print Node.js version'
        run: |
          echo abcdef > abc.txt
          git add abc.txt
          git -c user.name=github-actions -c user.email=github-actions@github.com commit -m 'Autocommit [skip ci]'
          git push
