name: 'Sample Workflow'
on:
  push:
    branches:
      - 'master'
jobs:
  hello:
    name: 'Hello Job'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'actions/setup-node@v3'
      - name: 'Print Node.js version'
        run: |
          echo abc > abc.txt
          git add abc.txt
          git -c user.name 'Jan Kowalski' -c user.email 'jan.kowalski@github.com' commit -m 'Auto'
